{{- $grafana := index .Values "kube-prometheus-stack" "grafana" -}}
{{ if and $grafana.enabled $grafana.sidecar.datasources.enabled -}}
{{- $tsdbExternalEnabled := .Values.timescaledbExternal.enabled -}}
{{- $tsdbDatasource := $grafana.timescale.datasource -}}
{{- $promEnabled := $grafana.prometheus.datasource.enabled -}}
{{- $anyDataSources := or $tsdbDatasource.enabled $promEnabled -}}
{{ if $anyDataSources -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  namespace: {{ template "tobs.namespace" . }}
  labels:
    tobs_datasource: "true"
    app: {{ template "tobs.fullname" . }}
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    datasources:
{{- if $promEnabled }}
      - name: Promscale
        type: prometheus
        url: {{ tpl $grafana.prometheus.datasource.url . }}
        isDefault: true
        editable: true
        access: proxy
{{- end -}}
{{ if $tsdbDatasource.enabled -}}
{{- $isDefault := not $promEnabled -}}
{{- $hostURL := "" -}}
{{ if $tsdbExternalEnabled -}}
  {{- $hostURL = include "tobs.dburi.host" . -}}
{{ else -}}
  {{- $host := tpl $grafana.timescale.database.host $ -}}
  {{- $port := $grafana.timescale.database.port | int -}}
  {{- $hostURL = printf "%s:%d" $host $port -}}
{{ end }}
      - name: TimescaleDB
        url: {{ $hostURL }}
        type: postgres
        isDefault: {{ $isDefault }}
        access: proxy
        user: {{ ternary (include "tobs.dburi.user" . ) ($tsdbDatasource.user) ($tsdbExternalEnabled) }}
        database: {{ ternary (include "tobs.dburi.dbname" . ) ($tsdbDatasource.dbName) ($tsdbExternalEnabled) }}
        editable: true
        secureJsonData:
          password: {{ ternary (include "tobs.dburi.password" . ) ($tsdbDatasource.pass) ($tsdbExternalEnabled) }}
        jsonData:
          sslmode: {{ ternary (include "tobs.dburi.sslmode" . ) ($tsdbDatasource.sslMode) ($tsdbExternalEnabled) }}
          postgresVersion: 1000
          timescaledb: true
{{- end -}}
{{- end -}}
{{- end -}}