{{ if eq .Values.connectionSecretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "promscale.fullname" . }}
  namespace: {{ template "promscale.namespace" . }}
  labels:
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  {{- if ne (.Values.connection.uri | toString) "" }}
  PROMSCALE_DB_URI: {{ .Values.connection.uri | toString | quote }}
  {{- else }}
  PROMSCALE_DB_PORT: {{ .Values.connection.port | toString | quote }}
  PROMSCALE_DB_USER: {{ .Values.connection.user | toString | quote }}
  PROMSCALE_DB_PASSWORD: {{ .Values.connection.password | toString | quote }}
  PROMSCALE_DB_HOST: {{ tpl .Values.connection.host . | toString | quote }}
  PROMSCALE_DB_NAME: {{ .Values.connection.dbName | toString | quote }}
  PROMSCALE_DB_SSL_MODE: {{ .Values.connection.sslMode | toString | quote }}
  {{- end }}
{{ end }}
