apiVersion: v1
kind: Service
metadata:
  name: {{ include "promscale.fullname" . | trunc 53 }}-connector
  namespace: {{ template "promscale.namespace" . }}
  labels:
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ template "promscale.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
  - name: metrics-port
    port: {{ .Values.prometheus.port }}
    protocol: TCP
  {{- if .Values.openTelemetry.enabled }}
  - name: otel-port
    port: {{ .Values.openTelemetry.port }}
    protocol: TCP
  {{- end }}
