{
 "title": "Postgres Details",
 "description": "Detailed performance metrics for Postgres",
 "tags": [ "postgres" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(postgres_exporter_build_info,instance)"
    }
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{instance=~\"$instance\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(postgres_exporter_build_info, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DB read / write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "rate(pg_stat_database_blk_read_time{datname=~\"$db\",datname!=\"\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ datname }}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "sum(rate(pg_stat_database_blk_read_time{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "rate(pg_stat_database_blk_write_time{datname=~\"$db\",datname!=\"\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ datname }}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "sum(rate(pg_stat_database_blk_write_time{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "sum"
    }
   ]
  },
  { "title": "Tuples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Inserted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "rate(pg_stat_database_tup_inserted{datname=~\"$db\",datname!=\"\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ datname }}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Fetched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "rate(pg_stat_database_tup_fetched{datname=~\"$db\",datname!=\"\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ datname }}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Returned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "rate(pg_stat_database_tup_returned{datname=~\"$db\",datname!=\"\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ datname }}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "sum"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Max duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "pg_stat_activity_max_tx_duration{datname=~\"$db\",datname!=\"\",instance=~\"$instance\",state=\"active\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ datname }}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "max(pg_stat_activity_max_tx_duration{datname=~\"$db\",datname!=\"\",instance=~\"$instance\",state=\"active\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "rate(pg_stat_database_xact_rollback{datname=~\"$db\",datname!=\"\",instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ datname }}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "sum"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "% requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "sum by (instance) (rate(pg_stat_bgwriter_checkpoints_req_total{instance=~\"$instance\"}[$__rate_interval])\n/\n(\n    rate(pg_stat_bgwriter_checkpoints_req_total{instance=~\"$instance\"}[$__rate_interval])\n    +\n    rate(pg_stat_bgwriter_checkpoints_timed_total{instance=~\"$instance\"}[$__rate_interval])\n))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance }}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "fetched",
     "expr": "sum by (instance) (delta(pg_stat_bgwriter_checkpoints_timed_total{instance=~\"$instance\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Timed - {{ instance }}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "expr": "sum by (instance) (delta(pg_stat_bgwriter_checkpoints_req_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Requested - {{ instance }}"
    }
   ]
  },
  { "title": "Buffers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Buffers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Checkpoint - {{ instance }}"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_backend_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Backend - {{ instance }}"
    },
    {
     "alias": "fetched",
     "expr": "rate(pg_stat_bgwriter_buffers_clean_total{instance=~\"$instance\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Clean - {{ instance }}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  }
 ]
}