name: Daily scheduled extended Go tests

on:
  push:
    branches: [force_test, release-*]
  schedule:
    - cron: "6 0 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./cli
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out master
        uses: actions/checkout@v2

      - name: Test static generation
        run: |
          ./generate-deploy-script.sh
          # git diff --exit-code

      - name: Format
        working-directory: ${{env.working-directory}}
        run: |
          make go-fmt

      - name: Vet
        working-directory: ${{env.working-directory}}
        run: |
          make go-vet

      - name: Lint
        working-directory: ${{env.working-directory}}
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
          golangci-lint run

      - name: Build
        working-directory: ${{env.working-directory}}
        run: |
          make build

      - name: Unit-Tests
        working-directory: ${{env.working-directory}}
        run: |
          make unit-tests

      - name: Helm-Tests
        working-directory: ${{env.working-directory}}
        run: |
          make helm-tests

      - name: Dependency-Tests
        working-directory: ${{env.working-directory}}
        run: |
          go test -v ./tests/dependency-tests

      - name: E2E-Tests
        working-directory: ${{env.working-directory}}
        run: |
          make e2e-tests

      - name: External-DB-Tests
        working-directory: ${{env.working-directory}}
        run: |
          make external-db-tests

      - name: Upgrade-Tests
        working-directory: ${{env.working-directory}}
        run: |
          make upgrade-tests

      - name: HA-Tests
        working-directory: ${{env.working-directory}}
        run: |
          make ha-tests

      - name: Install-Tests
        working-directory: ${{env.working-directory}}
        run: |
          make install-tests